server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/regdb
    username: postgres
    password: poo123@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true