server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/regdb
spring.datasource.username=postgres
spring.datasource.password=poo123@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.docker.compose.enabled=false

# Expose actuator endpoints for development
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always